name: 'Swift Build and Test'
description: 'Build and test Swift projects'
inputs:
  scheme:
    description: 'The Xcode scheme to build'
    required: true
  project:
    description: 'The Xcode project file'
    required: true
  simulator:
    description: 'The simulator ID or name to use'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Ruby and Bundler
      run: |
        brew install ruby
        gem install bundler
    - name: Install Bundler Dependencies
      run: |
        bundle install
    - name: Build Project
      run: |
        set -eo pipefail
        xcodebuild -scheme ${{ inputs.scheme }} -derivedDataPath "./DerivedData" build -destination "platform=iOS Simulator,name=${{ inputs.simulator }}" -UseModernBuildSystem=YES -project ${{ inputs.project }} | xcpretty
